---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: posterizarr
  namespace: media
spec:
  dataFrom:
    - extract:
        key: kometa
    - extract:
        key: plex
    - extract:
        key: posterizarr
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: posterizarr-secret
    template:
      data:
        FANARTTV_API_KEY: "{{ .FANARTTV_API_KEY }}"
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        TMDB_READ_API_TOKEN: "{{ .TMDB_API_KEY }}"
        TVDB_API_KEY: "{{ .TVDB_API_KEY }}"
