# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app posterizarr
spec:
  chartRef:
    kind: OCIRepository
    name: posterizarr
  interval: 1h
  timeout: 10m
  values:
    controllers:
      posterizarr:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: docker.io/mikefarah/yq
              tag: 4.52.1@sha256:c0f7a8a84f1dbfb7a19530683788dde8fc41227c7a2446a9d89d1e7eb9bad0a5
            command:
              - "/bin/sh"
            args:
              - "/app/config-file/init-config.sh"
            envFrom:
              - secretRef:
                  name: posterizarr-secret
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 128Mi
        containers:
          app:
            image:
              repository: ghcr.io/fscorrupt/posterizarr
              tag: 3.3.6@sha256:a5dc887ef9171306489bd0c513f3a24fb6b678ec713c46dda24a444fc01f7b57
            env:
              TZ: Europe/Berlin
              RUN_TIME: "03:00"
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8000
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 60
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8000
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8000
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
            resources:
              requests:
                cpu: 100m
                memory: 2048Mi
              limits:
                memory: 4096Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
          logs:
            image:
              repository: mirror.gcr.io/library/busybox
              tag: "1.38"
            command:
              - /bin/sh
              - -c
              - tail -n0 -F /config/UILogs/BackendServer.log
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 64Mi
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: node02
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    persistence:
      overlay-files:
        type: configMap
        name: posterizarr-overlay-files
        advancedMounts:
          posterizarr:
            app:
              - path: /app/Overlayfiles/BebasNeue-Regular.ttf
                subPath: BebasNeue-Regular.ttf
                readOnly: true
      config:
        accessMode: ReadWriteOnce
        enabled: true
        size: 5Gi
        storageClass: local-hostpath
        type: persistentVolumeClaim
      config-file:
        type: configMap
        defaultMode: 511
        name: posterizarr-configmap
        globalMounts:
          - path: /app/config-file
      ui-logs:
        type: emptyDir
        globalMounts:
          - path: /config/UILogs
      assets:
        existingClaim: posterizarr-assets-pvc
        globalMounts:
          - path: /assets
            subPath: assets
          - path: /manualassets
            subPath: manualassets
          - path: /assetsbackup
            subPath: assetsbackup
    route:
      app:
        annotations:
          gethomepage.dev/description: Movie and TV poster generation
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media Automation
          gethomepage.dev/href: https://posterizarr.${SECRET_DOMAIN}
          gethomepage.dev/icon: posterizarr.png
          gethomepage.dev/name: Posterizarr
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        controller: posterizarr
        ports:
          http:
            port: &port 8000
