---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rfc2136-dns
spec:
  dataFrom:
    - extract:
        key: rfc2136-dns
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rfc2136-dns-secret
    template:
      data:
        tsig-secret: "{{ .RFC2136_TSIG_SECRET }}"
        tsig-keyname: "{{ .RFC2136_TSIG_KEYNAME }}"
        host: "{{ .RFC2136_HOST }}"
        port: "{{ .RFC2136_PORT }}"
        zone: "{{ .RFC2136_ZONE }}"
