---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rfc2136-dns
spec:
  dataFrom:
    - extract:
        key: rfc2136-dns
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rfc2136-dns-secret
    template:
      data:
        RFC2136_TSIG_SECRET: "{{ .RFC2136_TSIG_SECRET }}"
        RFC2136_TSIG_KEYNAME: "{{ .RFC2136_TSIG_KEYNAME }}"
