# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: it-tools
  values:
    controllers:
      it-tools:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/it-tools
              tag: 2024.10.22@sha256:7f26ae8d7a4a58b8d70b685cba5cbaa54d7df876d9f8bae702207f45b06d9b7c
            env:
              TZ: Europe/Berlin
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 50Mi
              limits:
                memory: 250Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        annotations:
          gethomepage.dev/description: Handy tools for developers
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Self-hosted
          gethomepage.dev/icon: it-tools.svg
          gethomepage.dev/name: IT-Tools
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 8080
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp