---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firecrawl
spec:
  dataFrom:
    - extract:
        key: firecrawl
    - extract:
        key: postgres
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: firecrawl-secret
    template:
      data:
        BULL_AUTH_KEY: "{{ .FIRECRAWL_BULL_AUTH_KEY }}"
        INIT_POSTGRES_DBNAME: firecrawl
        INIT_POSTGRES_HOST: postgres18-firecrawl-rw.dbms.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .FIRECRAWL_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_USER: firecrawl
        NUQ_DATABASE_URL: postgresql://firecrawl:{{ .FIRECRAWL_POSTGRES_PASS }}@postgres18-firecrawl-rw.dbms.svc.cluster.local:5432/firecrawl
        NUQ_RABBITMQ_URL: amqp://firecrawl:{{ .FIRECRAWL_RABBITMQ_PASS }}@firecrawl-rabbitmq.ai.svc.cluster.local:5672
        OPENAI_API_KEY: "{{ .FIRECRAWL_OPENAI_API_KEY }}"
        RABBITMQ_DEFAULT_PASS: "{{ .FIRECRAWL_RABBITMQ_PASS }}"
