---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - ./resources/nuq.sql
    name: firecrawl-configmap
    options:
      annotations:
        # nuq.sql contains $$ blocks which must not be touched by flux substitution
        kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - ./resources/kustomizeconfig.yaml
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
