---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-files
spec:
  dataFrom:
    - extract:
        key: telegram-files
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: telegram-files-secret
    template:
      data:
        TELEGRAM_API_ID: "{{ .TELEGRAM_API_ID }}"
        TELEGRAM_API_HASH: "{{ .TELEGRAM_API_HASH }}"

