---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sons-of-the-forest-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sons-of-the-forest-secret
    template:
      data:
        # Configuration
        dedicatedserver.cfg: |
          {
            "IpAddress": "0.0.0.0",
            "GamePort": 8766,
            "QueryPort": 27016,
            "BlobSyncPort": 9700,
            "ServerName": "{{ .SOTF_SERVER_NAME }}",
            "MaxPlayers": 8,
            "Password": "{{ .SOTF_SERVER_PASSWORD }}",
            "LanOnly": false,
            "SaveSlot": 1,
            "SaveMode": "Continue",
            "GameMode": "Normal",
            "SaveInterval": 600,
            "IdleDayCycleSpeed": 0.0,
            "IdleTargetFramerate": 5,
            "ActiveTargetFramerate": 60,
            "LogFilesEnabled": false,
            "TimestampLogFilenames": true,
            "TimestampLogEntries": true,
            "SkipNetworkAccessibilityTest": true,
            "GameSettings": {},
            "CustomGameModeSettings": {}
          }
  dataFrom:
  - extract:
      key: sons-of-the-forest