---
libraries:
  Filme:
    collection_files:
      - file: /config/filme.yml
      - default: universe
        template_variables: &universe-settings
          use_all: false
          use_star: true
          name_star: Star Wars Collection
          file_poster_star: /config/posters/universe/Star-Wars.jpg
          language: de
          use_separator: true
          sep_style: blue
          name_separator: Sagas
          minimum_items: 1
          collection_mode: hide
          collection_order: release
          sync_mode: sync
      - default: genre
        template_variables: &genre-posters
          file_poster_Action: /config/posters/genre/Action.jpg
          file_poster_Adventure: /config/posters/genre/Adventure.jpg
          file_poster_Animation: /config/posters/genre/Animation.jpg
          file_poster_Anime: /config/posters/genre/Anime.jpg
          file_poster_Biopic: /config/posters/genre/Biopic.jpg
          file_poster_Komödie: /config/posters/genre/Comedy.jpg
          file_poster_Krimi: /config/posters/genre/Crime.jpg
          file_poster_Dokumentarfilm: /config/posters/genre/Documentaries.jpg
          file_poster_Drama: /config/posters/genre/Drama.jpg
          file_poster_Familie: /config/posters/genre/Family.jpg
          file_poster_Fantasy: /config/posters/genre/Fantasy.jpg
          file_poster_Historie: /config/posters/genre/History.jpg
          file_poster_Horror: /config/posters/genre/Horror.jpg
          file_poster_Martial Arts: /config/posters/genre/Martial-Arts.jpg
          file_poster_Mystery: /config/posters/genre/Mystery.jpg
          file_poster_Liebesfilm: /config/posters/genre/Romance.jpg
          file_poster_Science Fiction: /config/posters/genre/Science-Fiction.jpg
          file_poster_Thriller: /config/posters/genre/Thriller.jpg
          file_poster_Suspense: /config/posters/genre/Thriller.jpg
          file_poster_War: /config/posters/genre/War.jpg
          file_poster_Kriegsfilm: /config/posters/genre/War.jpg
          language: de
          name_format: <<key_name>> Filme
          sort_by: release.desc
          use_separator: true
          sep_style: blue
          name_separator: Genres
    settings:
      asset_directory: /assets/Filme
      prioritize_assets: false
    template_variables:
      collection_mode: hide
    operations:
      assets_for_all: true

  Serien:
    collection_files:
      - file: /config/serien.yml
      - default: universe
        template_variables: *universe-settings
      - default: genre
        template_variables:
          <<: *genre-posters
          file_poster_Mini-Series: /config/posters/genre/Mini-Series.jpg
          language: de
          name_format: <<key_name>> Serien
          sort_by: release.desc
          use_separator: false
          sep_style: blue
          name_separator: Genres
    settings:
      asset_directory: /assets/Serien
      prioritize_assets: false
    template_variables:
      collection_mode: hide
    operations:
      assets_for_all: true

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  create_asset_folders: false
  download_url_assets: true
  sync_mode: sync
  minimum_items: 5
  delete_below_minimum: true
  delete_not_scheduled: false
  default_collection_order:
  item_refresh_delay: 0
  run_again_delay: 2
  show_unmanaged: false
  show_unconfigured: false
  show_filtered: false
  show_missing: false
  show_options: false
  save_report: false
  verify_ssl: true
  check_nightly: false

plex:
  url: http://plex.media.svc.cluster.local:32400
  token: <<PLEX_API_KEY>>
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false

mdblist:
  apikey: <<MDBLIST_API_KEY>>
  cache_expiration: 60

tmdb:
  apikey: <<TMDB_API_KEY>>
  language: de
  cache_expiration: 60
  region:
