---
templates:
  universe:
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    minimum_items: 1
    sort_title: "!040_<<collection_name>>"

collections:
  Angesagte Filme:
    collection_mode: hide
    file_poster: /config/posters/genre/Trending.jpg
    mdblist_list: https://mdblist.com/lists/beetbytes/german-most-popular-top-50-released-within-132d
    collection_order: custom
    sync_mode: sync
    sort_title: "!001_Angesagte Filme"
    summary: Die derzeit meistgesehenen Filme.
    visible_home: true
    visible_shared: true

  Matrix Collection:
    template:
      name: universe
    tmdb_collection_details: 2344
    file_poster: /config/posters/universe/Matrix.jpg

  Der Pate Collection:
    template:
      name: universe
    tmdb_collection_details: 230
    file_poster: /config/posters/universe/The-Godfather.jpg
