---
collections:
  Derzeit beliebt:
    mdblist_list: https://mdblist.com/lists/beetbytes/german-monthly-streaming-charts-last-aired-within-365d
    collection_order: custom
    sync_mode: sync
    sort_title: "!001_Derzeit beliebt"
    summary: Die derzeit meistgesehenen Serien.
    visible_home: true
    visible_shared: true
