model_list:
  - model_name: github_copilot/gpt-5-mini
    litellm_params:
      model: github_copilot/gpt-5-mini
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-5
    litellm_params:
      model: github_copilot/gpt-5
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4o-mini-2024-07-18
    litellm_params:
      model: github_copilot/gpt-4o-mini-2024-07-18
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4o-2024-11-20
    litellm_params:
      model: github_copilot/gpt-4o-2024-11-20
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4o-2024-08-06
    litellm_params:
      model: github_copilot/gpt-4o-2024-08-06
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/grok-code-fast-1
    litellm_params:
      model: github_copilot/grok-code-fast-1
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-5.1
    litellm_params:
      model: github_copilot/gpt-5.1
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-5.1-codex
    model_info:
      mode: responses
    litellm_params:
      model: github_copilot/gpt-5.1-codex
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-5.1-codex-mini
    model_info:
      mode: responses
    litellm_params:
      model: github_copilot/gpt-5.1-codex-mini
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-5.1-codex-max
    model_info:
      mode: responses
    litellm_params:
      model: github_copilot/gpt-5.1-codex-max
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-5-codex
    model_info:
      mode: responses
    litellm_params:
      model: github_copilot/gpt-5-codex
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/text-embedding-3-small
    model_info:
      mode: embedding
    litellm_params:
      model: github_copilot/text-embedding-3-small
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/text-embedding-3-small-inference
    model_info:
      mode: embedding
    litellm_params:
      model: github_copilot/text-embedding-3-small-inference
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/claude-sonnet-4
    litellm_params:
      model: github_copilot/claude-sonnet-4
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/claude-sonnet-4.5
    litellm_params:
      model: github_copilot/claude-sonnet-4.5
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/claude-opus-4.5
    litellm_params:
      model: github_copilot/claude-opus-4.5
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/claude-haiku-4.5
    litellm_params:
      model: github_copilot/claude-haiku-4.5
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gemini-3-pro-preview
    litellm_params:
      model: github_copilot/gemini-3-pro-preview
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gemini-3-flash-preview
    litellm_params:
      model: github_copilot/gemini-3-flash-preview
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gemini-2.5-pro
    litellm_params:
      model: github_copilot/gemini-2.5-pro
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4.1-2025-04-14
    litellm_params:
      model: github_copilot/gpt-4.1-2025-04-14
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/oswe-vscode-prime
    litellm_params:
      model: github_copilot/oswe-vscode-prime
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/oswe-vscode-secondary
    litellm_params:
      model: github_copilot/oswe-vscode-secondary
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-5.2
    litellm_params:
      model: github_copilot/gpt-5.2
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-41-copilot
    litellm_params:
      model: github_copilot/gpt-41-copilot
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-3.5-turbo-0613
    litellm_params:
      model: github_copilot/gpt-3.5-turbo-0613
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4
    litellm_params:
      model: github_copilot/gpt-4
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4-0613
    litellm_params:
      model: github_copilot/gpt-4-0613
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4-0125-preview
    litellm_params:
      model: github_copilot/gpt-4-0125-preview
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4o-2024-05-13
    litellm_params:
      model: github_copilot/gpt-4o-2024-05-13
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4-o-preview
    litellm_params:
      model: github_copilot/gpt-4-o-preview
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4.1
    litellm_params:
      model: github_copilot/gpt-4.1
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-3.5-turbo
    litellm_params:
      model: github_copilot/gpt-3.5-turbo
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4o-mini
    litellm_params:
      model: github_copilot/gpt-4o-mini
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/gpt-4o
    litellm_params:
      model: github_copilot/gpt-4o
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: github_copilot/text-embedding-ada-002
    model_info:
      mode: embedding
    litellm_params:
      model: github_copilot/text-embedding-ada-002
      extra_headers:
        {
          "Editor-Version": "vscode/1.85.1",
          "Copilot-Integration-Id": "vscode-chat",
        }

general_settings:
  proxy_batch_write_at: 60
  database_connection_pool_limit: 10
  use_redis_transaction_buffer: true


  disable_error_logs: True
  allow_requests_on_db_unavailable: True

router_settings:
  routing_strategy: usage-based-routing-v2
  redis_host: os.environ/REDIS_HOST

litellm_settings:
  set_verbose: False
  json_logs: true
  cache: True
  cache_params:
    type: redis
