---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../securitypolicy.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/values/route/authentik-callback
        value:
          enabled: true
          hostnames:
            - "${EXT_AUTH_HOSTNAME:-${APP}.${SECRET_DOMAIN}}"
          parentRefs:
            - name: envoy-external
              namespace: network
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /outpost.goauthentik.io
              backendRefs:
                - name: authentik-outpost-proxy
                  namespace: security
                  port: 9000
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: ${APP}
