---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: archon
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: archon-secret
    template:
      data:
        # AI Assistant
        CODEX_ID_TOKEN: "{{ .ARCHON_CODEX_ID_TOKEN }}"
        CODEX_ACCESS_TOKEN: "{{ .ARCHON_CODEX_ACCESS_TOKEN }}"
        CODEX_REFRESH_TOKEN: "{{ .ARCHON_CODEX_REFRESH_TOKEN }}"
        CODEX_ACCOUNT_ID: "{{ .ARCHON_CODEX_ACCOUNT_ID }}"
        # Database
        DATABASE_URL: "postgresql://{{ .ARCHON_POSTGRES_USER }}:{{ .ARCHON_POSTGRES_PASSWORD }}@postgres18.dbms.svc.cluster.local:5432/{{ .ARCHON_POSTGRES_DB }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .ARCHON_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: postgres18.dbms.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .ARCHON_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .ARCHON_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Telegram
        TELEGRAM_BOT_TOKEN: "{{ .ARCHON_TELEGRAM_BOT_TOKEN }}"
        TELEGRAM_ALLOWED_USER_IDS: "{{ .ARCHON_TELEGRAM_ALLOWED_USER_IDS }}"
        # Discord
        DISCORD_BOT_TOKEN: "{{ .ARCHON_DISCORD_BOT_TOKEN }}"
        DISCORD_ALLOWED_USER_IDS: "{{ .ARCHON_DISCORD_ALLOWED_USER_IDS }}"
        # Github
        WEBHOOK_SECRET: "{{ .ARCHON_GITHUB_WEBHOOK_SECRET }}"
  dataFrom:
  - extract:
      key: postgres
  - extract:
      key: archon
