---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prunerr
spec:
  dataFrom:
    - extract:
        key: prunerr
    - extract:
        key: seerr
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: plex
    - extract:
        key: tautulli
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: prunerr-secret
    template:
      data:
        DISCORD_WEBHOOK_URL: "{{ .PRUNERR_DISCORD_WEBHOOK_URL }}"
        OVERSEERR_API_KEY: "{{ .SEERR_API_KEY }}"
        OVERSEERR_URL: http://seerr.downloads.svc.cluster.local:5055
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        PLEX_URL: http://plex.media.svc.cluster.local:32400
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        RADARR_URL: http://radarr.downloads.svc.cluster.local:80
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        SONARR_URL: http://sonarr.downloads.svc.cluster.local:80
        TAUTULI_API_KEY: "{{ .TAUTULI_API_KEY }}"
        TAUTULI_URL: http://tautulli.media.svc.cluster.local:8181
