---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spotify-to-plex
  namespace: self-hosted
spec:
  dataFrom:
    - extract:
        key: spotify-to-plex
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: spotify-to-plex-secret
    template:
      data:
        SPOTIFY_API_CLIENT_ID: "{{ .SPOTIFY_API_CLIENT_ID }}"
        SPOTIFY_API_CLIENT_SECRET: "{{ .SPOTIFY_API_CLIENT_SECRET }}"
        SPOTIFY_API_REDIRECT_URI: "{{ .SPOTIFY_API_REDIRECT_URI }}"
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        PLEX_APP_ID: "{{ .PLEX_APP_ID }}"
        LIDARR_API_KEY: "{{ .LIDARR_API_KEY }}"
