# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spotify-to-plex
spec:
  chartRef:
    kind: OCIRepository
    name: spotify-to-plex
  interval: 1h
  values:
    controllers:
      spotify-to-plex:
        containers:
          app:
            env:
              PORT: 80
            envFrom:
              - secretRef:
                  name: spotify-to-plex-secret
            image:
              repository: jjdenhertog/spotify-to-plex
              tag: 1.0.104@sha256:5a3f03976c9abb4c71587664e361671c0db7188974e34b6ac3d52abf6aff26ef
            probes:
              liveness: &probes
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              limits:
                memory: 1Gi
              requests:
                memory: 128Mi
                cpu: 10m
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: true
        strategy: RollingUpdate
    defaultPodOptions:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    route:
      app:
        annotations:
          gethomepage.dev/description: Sync your Spotify playlists to Plex and keep them up to date.
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Self-hosted
          gethomepage.dev/name: Spotify to Plex
        hostnames: ["spotify-sync.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 80
    persistence:
      tmpfs:
        globalMounts:
          - path: /tmp
        type: emptyDir
    service:
      app:
        ports:
          http:
            port: 80
