---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube
spec:
  dataFrom:
    - extract:
        key: sonarqube
    - extract:
        key: postgres
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sonarqube-secret
    template:
      data:
        INIT_POSTGRES_DBNAME: "{{ .POSTGRES_DB }}"
        INIT_POSTGRES_HOST: postgres18.dbms.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        SONAR_JDBC_USERNAME: "{{ .POSTGRES_USER }}"
        SONAR_JDBC_PASSWORD: "{{ .POSTGRES_PASS }}"
        SONAR_JDBC_URL: "jdbc:postgresql://postgres18.dbms.svc.cluster.local:5432/{{ .POSTGRES_DB }}"
