---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tv-charts-prune
spec:
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: tautulli
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tv-charts-prune-secret
    template:
      data:
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
