# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: archon
  namespace: self-hosted
spec:
  components:
    - ../../../../components/ext-auth/external
  dependsOn:
    - name: onepassword-connect
      namespace: kube-system
    - name: cloudnative-pg-cluster
      namespace: dbms
  interval: 1h
  path: ./kubernetes/apps/self-hosted/archon/app
  postBuild:
    substitute:
      APP: archon
      EXT_AUTH_APP: archon
      EXT_AUTH_TARGET_NAME: archon
      EXT_AUTH_HOSTNAME: archon.${SECRET_DOMAIN}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  wait: false
