# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea-runner
spec:
  chartRef:
    kind: OCIRepository
    name: gitea-runner
  install:
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 3
  uninstall:
    keepHistory: false
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      gitea-runner:
        type: statefulset
        replicas: 3
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          runner:
            env:
              GITEA_INSTANCE_URL: http://gitea.self-hosted.svc.cluster.local
              ACT_CACHE_SERVER_DIR: /cache/server
              GITEA_RUNNER_ACTION_CACHE_DIR: /cache/actions
              TZ: Europe/Berlin
            envFrom:
              - secretRef:
                  name: gitea-runner-secret
            image:
              pullPolicy: IfNotPresent
              repository: ghcr.io/vegardit/gitea-act-runner
              tag: dind-0.3.1@sha256:7a697aa40e3adb8c9714fa10dbc6c8df1436b2a0afe18a96fb477cbc45aba53f
            securityContext:
              privileged: true
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: local-hostpath
        advancedMounts:
          gitea-runner:
            runner:
              - path: /data
      cache:
        enabled: true
        type: emptyDir
        advancedMounts:
          gitea-runner:
            runner:
              - path: /cache
      docker-storage:
        enabled: true
        type: emptyDir
        advancedMounts:
          gitea-runner:
            runner:
              - path: /var/lib/docker
    service:
      main:
        enabled: false