# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea-runner
spec:
  chartRef:
    kind: OCIRepository
    name: gitea-runner
  install:
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 3
  uninstall:
    keepHistory: false
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      runner:
        type: statefulset
        replicas: 3
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              GITEA_INSTANCE_URL: http://gitea.self-hosted.svc.cluster.local
              ACT_CACHE_SERVER_DIR: /cache/server
              GITEA_RUNNER_ACTION_CACHE_DIR: /cache/actions
              GITEA_RUNNER_JOB_CONTAINER_NETWORK: host
              GITEA_RUNNER_JOB_CONTAINER_PRIVILEGED: "true"
              TZ: Europe/Berlin
            envFrom:
              - secretRef:
                  name: gitea-runner-secret
            image:
              pullPolicy: Always
              repository: ghcr.io/vegardit/gitea-act-runner
              tag: dind-0.3.0@sha256:8e415c329f6351ab32b7bd12f30316e0f6c877bd97fef5bc3a86598335e424c5
            securityContext:
              privileged: true
              appArmorProfile:
                type: Unconfined
              seccompProfile:
                type: Unconfined
        pod:
          securityContext:
            seccompProfile:
              type: Unconfined
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: local-hostpath
        advancedMounts:
          runner:
            app:
              - path: /data
      cache:
        enabled: true
        type: emptyDir
        advancedMounts:
          runner:
            app:
              - path: /cache
      docker-storage:
        enabled: true
        type: emptyDir
        advancedMounts:
          runner:
            app:
              - path: /var/lib/docker
    service:
      main:
        enabled: false