---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse
  namespace: ai
spec:
  dataFrom:
    - extract:
        key: langfuse
    - extract:
        key: postgres
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: langfuse-secret
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .LANGFUSE_S3__ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .LANGFUSE_S3__SECRET_ACCESS_KEY }}"
        AUTH_AUTHENTIK_CLIENT_ID: "{{ .AUTH_AUTHENTIK_CLIENT_ID }}"
        AUTH_AUTHENTIK_CLIENT_SECRET: "{{ .AUTH_AUTHENTIK_CLIENT_SECRET }}"
        AUTH_AUTHENTIK_ISSUER: "{{ .AUTH_AUTHENTIK_ISSUER }}"
        CLICKHOUSE_PASSWORD: "{{ .CLICKHOUSE_PASSWORD }}"
        CLICKHOUSE_USER: "{{ .CLICKHOUSE_USER }}"
        DATABASE_HOST: postgres18.dbms.svc.cluster.local
        DATABASE_NAME: langfuse
        DATABASE_PASSWORD: "{{ .POSTGRES_PASS }}"
        DATABASE_USER: "{{ .POSTGRES_USER }}"
        DATABASE_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres18.dbms.svc.cluster.local:5432/langfuse"
        EMAIL_FROM_ADDRESS: "{{ .LANGFUSE_EMAIL__FROM_ADDRESS }}"
        ENCRYPTION_KEY: "{{ .LANGFUSE_ENCRYPTION__KEY }}"
        INIT_POSTGRES_DBNAME: langfuse
        INIT_POSTGRES_HOST: postgres18.dbms.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        LANGFUSE_INIT_ORG_ID: "{{ .LANGFUSE_INIT__ORG__ID }}"
        LANGFUSE_INIT_ORG_NAME: "{{ .LANGFUSE_INIT__ORG__NAME }}"
        LANGFUSE_INIT_PROJECT_ID: "{{ .LANGFUSE_INIT__PROJECT__ID }}"
        LANGFUSE_INIT_PROJECT_NAME: "{{ .LANGFUSE_INIT__PROJECT__NAME }}"
        LANGFUSE_INIT_PROJECT_PRIVATE_KEY: "{{ .LANGFUSE_INIT__PROJECT__PRIVATE__KEY }}"
        LANGFUSE_INIT_PROJECT_PUBLIC_KEY: "{{ .LANGFUSE_INIT__PROJECT__PUBLIC__KEY }}"
        LANGFUSE_INIT_USER_EMAIL: "{{ .LANGFUSE_INIT__USER__EMAIL }}"
        LANGFUSE_INIT_USER_PASSWORD: "{{ .LANGFUSE_INIT__USER__PASSWORD }}"
        LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID: "{{ .LANGFUSE_S3__ACCESS_KEY_ID }}"
        LANGFUSE_S3_BATCH_EXPORT_BUCKET: "{{ .LANGFUSE_S3__BUCKET }}"
        LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY: "{{ .LANGFUSE_S3__SECRET_ACCESS_KEY }}"
        LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: "{{ .LANGFUSE_S3__ACCESS_KEY_ID }}"
        LANGFUSE_S3_EVENT_UPLOAD_BUCKET: "{{ .LANGFUSE_S3__BUCKET }}"
        LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: "{{ .LANGFUSE_S3__SECRET_ACCESS_KEY }}"
        LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: "{{ .LANGFUSE_S3__ACCESS_KEY_ID }}"
        LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: "{{ .LANGFUSE_S3__BUCKET }}"
        LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: "{{ .LANGFUSE_S3__SECRET_ACCESS_KEY }}"
        NEXTAUTH_SECRET: "{{ .LANGFUSE_NEXTAUTH__SECRET }}"
        REDIS_HOST: dragonfly.dbms.svc.cluster.local
        S3_BUCKET: "{{ .LANGFUSE_S3__BUCKET }}"
        SALT: "{{ .LANGFUSE_SALT }}"
