---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plextraktsync
  namespace: media
spec:
  dataFrom:
    - extract:
        key: plex
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plextraktsync-secret
    template:
      data:
        PLEX_USERNAME: "{{ .PLEXTRAKTSYNC_PLEX_USERNAME }}"
        TRAKT_USERNAME: "{{ .PLEXTRAKTSYNC_TRAKT_USERNAME }}"
        PLEX_SERVER: "{{ .PLEXTRAKTSYNC_PLEX_SERVER_NAME }}"
        servers.yml: |
          servers:
            default:
              token: null
              urls:
              - null
              - null
            {{ .PLEXTRAKTSYNC_PLEX_SERVER_NAME }}:
              token: {{ .PLEXTRAKTSYNC_PLEX_TOKEN }}
              urls:
              - http://192.168.178.128:32400
              - http://10.42.0.95:32400
              - https://plex.${SECRET_DOMAIN}:443
              - http://plex.default.svc.cluster.local:32400
              - http://plex.${SECRET_DOMAIN}:443
        .pytrakt.json: |
          {
            "APPLICATION_ID": null,
            "CLIENT_ID": "{{ .PLEXTRAKTSYNC_OAUTH_CLIENT_ID }}",
            "CLIENT_SECRET": "{{ .PLEXTRAKTSYNC_OAUTH_CLIENT_SECRET }}",
            "OAUTH_EXPIRES_AT": {{ .PLEXTRAKTSYNC_OAUTH_EXPIRES_AT }},
            "OAUTH_REFRESH": "{{ .PLEXTRAKTSYNC_OAUTH_REFRESH }}",
            "OAUTH_TOKEN": "{{ .PLEXTRAKTSYNC_OAUTH_TOKEN }}"
          }
        config.yml : |
          cache:
            path: $PTS_CACHE_DIR/trakt_cache

          excluded-libraries:
            - R&D
            - Musik
            - Hörbücher

          config:
            dotenv_override: false

          plex:
            timeout: 30

          logging:
            append: true
            console_time: false
            debug: false
            filename: plextraktsync.log

          sync:
            plex_to_trakt:
              collection: true
              clear_collected: false
              ratings: true
              watched_status: true
              watchlist: false
            trakt_to_plex:
              liked_lists: true
              ratings: true
              watched_status: true
              watchlist: true
              watchlist_as_playlist: false

          watch:
            add_collection: false
            remove_collection: false
            scrobble_threshold: 80
            username_filter: true
            media_progressbar: true

          xbmc-providers:
            movies: imdb
            shows: tvdb
