---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plextraktsync
spec:
  chartRef:
    kind: OCIRepository
    name: plextraktsync
  interval: 1h
  values:
    controllers:
      plextraktsync:
        type: cronjob
        cronjob:
          schedule: 0 6,18 * * *
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 18000
          timeZone: Europe/Berlin
        containers:
          app:
            image:
              repository: ghcr.io/taxel/plextraktsync
              tag: 0.35.6@sha256:7bd8ea208f35e9b83524504dca7cafb194a568993814965b554aca22dcc64a35
            envFrom:
              - secretRef:
                  name: plextraktsync-secret
            env:
              TZ: Europe/Berlin
            args:
              - sync
        pod:
          restartPolicy: Never
    persistence:
      config-file:
        type: secret
        name: plextraktsync-secret
        globalMounts:
          - path: /app/config/config.yml
            subPath: config.yml
      servers-file:
        type: secret
        name: plextraktsync-secret
        globalMounts:
          - path: /app/config/servers.yml
            subPath: servers.yml
      pytrakt-file:
        type: secret
        name: plextraktsync-secret
        globalMounts:
          - path: /app/config/.pytrakt.json
            subPath: .pytrakt.json
