---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nas-resticprofile
spec:
  chartRef:
    kind: OCIRepository
    name: nas-resticprofile
  interval: 1h
  values:
    controllers:
      backup:
        type: cronjob
        cronjob:
          schedule: 0 0 * * 1
          timeZone: Europe/Berlin
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 18000
        containers:
          app:
            image:
              repository: ghcr.io/creativeprojects/resticprofile
              tag: 0.33.1@sha256:1ed251a2f9b5f87720362958d6e02a7aed96ccc50d3ca7b8bb23a45559db7290
            envFrom: &envFrom
              - secretRef:
                  name: nas-resticprofile-secret
            env:
              TZ: Europe/Berlin
            args:
              - -c
              - /resticprofile/profiles.yaml
              - --profile
              - nas
              - backup
        pod:
          restartPolicy: Never
      check:
        type: cronjob
        cronjob:
          schedule: 0 0 1 * *
          timeZone: Europe/Berlin
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 18000
        containers:
          app:
            image:
              repository: ghcr.io/creativeprojects/resticprofile
              tag: 0.33.1@sha256:1ed251a2f9b5f87720362958d6e02a7aed96ccc50d3ca7b8bb23a45559db7290
            envFrom: *envFrom
            env:
              TZ: Europe/Berlin
            args:
              - -c
              - /resticprofile/profiles.yaml
              - --profile
              - nas
              - check
        pod:
          restartPolicy: Never
    persistence:
      key-file:
        type: secret
        name: nas-resticprofile-secret
        globalMounts:
          - path: /resticprofile/backup-key
            subPath: backup-key
      profiles-file:
        type: secret
        name: nas-resticprofile-secret
        globalMounts:
          - path: /resticprofile/profiles.yaml
            subPath: profiles.yaml
      nas:
        type: nfs
        server: nas.internal
        path: /nas
        globalMounts:
          - path: /nas/home-assistant
            subPath: home-assistant
          - path: /nas/photos
            subPath: photos
          - path: /nas/paperless
            subPath: paperless
          - path: /nas/backups/postgres
            subPath: backups/postgres
          - path: /nas/backups/tautulli
            subPath: backups/tautulli

