---
apiVersion: v1
kind: ConfigMap
metadata:
  name: langfuse-seaweedfs-configmap
data:
  lifecycle.json: |
    {
      "Rules": [
        {
          "ID": "expire-after-90-days",
          "Status": "Enabled",
          "Filter": {
            "Prefix": ""
          },
          "Expiration": {
            "Days": 90
          }
        }
      ]
    }
