---
radarrEnabled: false
sonarrEnabled: true
lidarrEnabled: false
readarrEnabled: false
whisparrEnabled: false

telemetry: false

sonarr:
  instance1:
    base_url: http://sonarr.downloads.svc.cluster.local
    api_key: !env SONARR_API_KEY

    quality_definition:
      type: series

    include:
      # [German] HD Bluray + WEB
      - template: dca7e5e9e99c703bcbdaaa471dd40e98
        source: TRASH

      # [German] Anime HD Bluray + WEB
      - template: 6fe5937e1dcc2269e23b49eb46dfe6d6
        source: TRASH

    renameQualityProfiles:
      - from: "[German] HD Bluray + WEB"
        to: "German"
