---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/configmap_v1.json
nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/values/persistence/config/name
        kind: HelmRelease
