---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: change-detection-0
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
