---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      - op: add
        path: /spec/rules/-
        value:
          matches:
            - path:
                type: PathPrefix
                value: /outpost.goauthentik.io
          backendRefs:
            - name: authentik-outpost-proxy
              namespace: security
              port: 9000
    target:
      group: ${EXT_AUTH_TARGET_GROUP:-gateway.networking.k8s.io}
      kind: ${EXT_AUTH_TARGET_KIND:-HTTPRoute}
      name: ${EXT_AUTH_TARGET_NAME:-${APP}}
