---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./securitypolicy.yaml
replacements:

  - source:
      kind: HTTPRoute
      name: ${EXT_AUTH_APP}
      fieldPath: spec.hostnames
    targets:
      - select:
          kind: HTTPRoute
          name: ${EXT_AUTH_APP}-auth-callback
        fieldPaths:
          - spec.hostnames

  - source:
      kind: HTTPRoute
      name: ${EXT_AUTH_APP}
      fieldPath: spec.parentRefs
    targets:
      - select:
          kind: HTTPRoute
          name: ${EXT_AUTH_APP}-auth-callback
        fieldPaths:
          - spec.parentRefs
