---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  dataFrom:
    - extract:
        key: slskd
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: slskd-secret
    template:
      data:
        SLSKD_API_KEY_HOMEPAGE: "{{ .SLSKD_API_KEY_HOMEPAGE }}"
        SLSKD_API_KEY_LIDARR: "{{ .SLSKD_API_KEY_LIDARR }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSKD_SLSK_PASSWORD }}"
        SLSKD_SLSK_USERNAME: "{{ .SLSKD_SLSK_USERNAME }}"
        SLSKD_VPN_GLUETUN_API_KEY: "{{ .SLSKD_HTTP_CONTROL_SERVER_AUTH_API_KEY}}"
        WIREGUARD_PRIVATE_KEY: "{{ .SLSKD_GLUETUN_WIREGUARD_PRIVATE_KEY }}"
        HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: |
          {
            "auth": "apikey",
            "apikey": "{{ .SLSKD_HTTP_CONTROL_SERVER_AUTH_API_KEY }}"
          }
        slskd.yml: |-
            web:
              authentication:
                api_keys:
                  lidarr:
                    key: {{ .SLSKD_API_KEY_LIDARR }}
                    cidr: 10.42.0.0/16
                  homepage_widget:
                    key: {{ .SLSKD_API_KEY_HOMEPAGE }}
                    role: ReadOnly
                    cidr: 10.42.0.0/16
            transfers:
              download:
                slots: 100
                retry:
                  incomplete: resume
                  attempts: 3
                  delay: 5000
                  max_delay: 60000
              upload:
                slots: 10
                speed_limit: 1500
            directories:
              downloads: /media/downloads/soulseek/complete
              incomplete: /media/downloads/soulseek/incomplete
            permissions:
              file:
                mode: 750
            shares:
              directories:
                - /media/media/audio
              filters:
                - \.ini$
                - Thumbs.db$
                - \.DS_Store$
            soulseek:
              listenPort: 50429
            integrations:
              vpn:
                enabled: true
                port_forwarding: true
                api_key: {{ .SLSKD_VPN_GLUETUN_API_KEY }}
                polling_interval: 2500
                gluetun:
                  url: http://localhost:8000
                  timeout: 1000
