# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app slskd
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    configMaps:
      config:
        data:
          slskd.yml: |-
            web:
              authentication:
                api_keys:
                  lidarr:
                    key: ${SLSKD_API_KEY_LIDARR}
                    cidr: 10.42.0.0/16
                  homepage_widget:
                    key: ${SLSKD_API_KEY_HOMEPAGE}
                    role: ReadOnly
                    cidr: 10.42.0.0/16
            transfers:
              upload:
                slots: 10
                speed_limit: 1500
            directories:
              downloads: /media/downloads/soulseek/complete
              incomplete: /media/downloads/soulseek/incomplete
            permissions:
              file:
                mode: 750
            shares:
              directories:
                - /media/media/audio
              filters:
                - \.ini$
                - Thumbs.db$
                - \.DS_Store$
            soulseek:
              listenPort: 50429
            integrations:
              vpn:
                enabled: true
                port_forwarding: true
                polling_interval: 2500
                gluetun:
                  url: http://localhost:8000
                  timeout: 1000
    controllers:
      slskd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp/.net
              SLSKD_APP_DIR: /config
              SLSKD_HTTP_PORT: &port 80
              SLSKD_NO_AUTH: true
              SLSKD_NO_HTTPS: true
              SLSKD_NO_VERSION_CHECK: true
              SLSKD_SLSK_LISTEN_PORT: 50429
              TZ: Europe/Berlin
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            image:
              repository: ghcr.io/slskd/slskd
              tag: 0.25.0@sha256:6a91991c05b7cbbe4e3dcc1f5e10f88d00a68f7ad2ef8a820b79496441b9b78c
            probes:
              liveness: &probes
                custom: true
                enabled: true
                spec:
                  failureThreshold: 8
                  httpGet:
                    port: 80
                    path: /
                  initialDelaySeconds: 120 # needed in case share scan started
                  periodSeconds: 60
                  timeoutSeconds: 10
              readiness: *probes
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 10m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
        initContainers:
          gluetun:
            env:
              FIREWALL_INPUT_PORTS: "80,9999"
              FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/16
              SERVER_COUNTRIES: Netherlands
              VPN_PORT_FORWARDING: on
              VPN_SERVICE_PROVIDER: protonvpn
              PORT_FORWARD_ONLY: on
              VPN_TYPE: wireguard
              TZ: Europe/Berlin
              UPDATER_PERIOD: 24h
              WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: 15s
              HEALTH_SERVER_ADDRESS: 0.0.0.0:9999
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.41@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
            ports:
              - containerPort: 80
                name: http
                protocol: TCP
            restartPolicy: Always
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 9999
                  initialDelaySeconds: 20
                  periodSeconds: 20
                  timeoutSeconds: 10
                  failureThreshold: 5
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 9999
                  initialDelaySeconds: 10
                  timeoutSeconds: 10
                  periodSeconds: 10
                  failureThreshold: 5
            resources:
              limits:
                squat.ai/tun: "1"
            securityContext:
              capabilities:
                add: ["NET_ADMIN", "NET_RAW"]
              privileged: true
              runAsGroup: 0
              runAsNonRoot: false
              runAsUser: 0
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    persistence:
      config:
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: local-hostpath
      config-file:
        globalMounts:
          - path: /config/slskd.yml
            subPath: slskd.yml
        identifier: config
        type: configMap
      media:
        globalMounts:
          - path: /media
        path: /media-root
        server: nas.internal
        type: nfs
      tmp:
        type: emptyDir
    route:
      slskd:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/icon: slskd.png
          gethomepage.dev/name: Slskd
          gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_SLSKD_API_KEY}}`}}"
          gethomepage.dev/widget.type: slskd
          gethomepage.dev/widget.url: http://slskd.downloads.svc.cluster.local:80
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
    service:
      slskd:
        controller: *app
        ports:
          http:
            port: *port
