---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark
spec:
  dataFrom:
    - extract:
        key: shelfmark
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: shelfmark-secret
    template:
      data:
        OIDC_CLIENT_SECRET: "{{ .SHELFMARK_OIDC_CLIENT_SECRET }}"
