---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulsarr
spec:
  dataFrom:
    - extract:
        key: pulsarr
    - extract:
        key: postgres
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pulsarr-secret
    template:
      data:
        dbHost: &dbhost "postgres18.dbms.svc.cluster.local"
        dbPort: "5432"
        dbUser: &dbuser "{{ .POSTGRES_USER }}"
        dbPassword: &dbpass "{{ .POSTGRES_PASS }}"
        dbName: &dbname "{{ .POSTGRES_DB }}"
        discordWebhookUrl: "{{ .PULSARR_DISCORD_WEBHOOK_URL }}"
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_USER: *dbuser

