apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:WCIbeS3y6ggWPITG,iv:yWyzHRbtBSkpSJs94gM/sQJoqI4IiXzyO693YT+HC24=,tag:LuYZNBubJBWWmuMH4Wbe8g==,type:str]
  S3_BACKUP_ENDPOINT: ENC[AES256_GCM,data:vtv1B5fdUul+JVLejAnT0nz93Wf3zjCA8jyU,iv:j5LymPj+G22YufqOD8nyxrKT4KR2DvFiB6nGEoL7B5I=,tag:BIfjsVV/3OketFiWGQoRbg==,type:str]
sops:
  age:
    - recipient: age1n3ql3mrczyduw5hxwcztsxxllfp7zwc6urxg4q6u20ras3whwuks8nqxvx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUFpMRlhVc1V0SjdIK2ky
        Rnhqd0lteXAvSm1zV29kZDlsczl2dVhXV2l3ClBEdHlXMVIrTzdMTHpsRW05UXdD
        OFpkN3lmUGppTlZWelFmdGVGTnpLUEEKLS0tIGJVdkp5OTloUFY1NTB0UzFNeDdQ
        bFZXY2NqOVN6bjJlRGdUaVNtNDlPY0UKvoNLI8cLRxDB9dc2rEEBYnYm/PkPkfJd
        4foMiJvuGDy5zyUmMjkyndLG/lFaontXvy8VIUTehI8/UXckVwIuOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T12:21:38Z"
  mac: ENC[AES256_GCM,data:HH+5eovL2FXsCxYP9nZ+noN6rmQfAKMF3/L45D0oTAv7Rvt+lPNifEkRVJhkLSyvQJ+3c7QYhSOtBsOcYBWudCAL1BjYLSA08hyMhPAgTb2cCm2BTpY7C6fRd+0PHmik96n+P4gUPcATSRg8wonKyaVqSix+RujuEaD29syV1jI=,iv:iwDJqG9JZmKW1hr+S6cvNE6VJ269eh84POnXaf+nkF8=,tag:ngAuYL3IRlr//uUTdJVHBg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
