---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kometa
spec:
  chartRef:
    kind: OCIRepository
    name: kometa
  interval: 1h
  values:
    controllers:
      kometa:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          schedule: 0 4 * * *
          timeZone: &timeZone Europe/Berlin
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 18000
        containers:
          app:
            image:
              repository: kometateam/kometa
              tag: v2.5.2@sha256:06e498cded70c9815522c6b2d8708b31759c1e37714746d1eeb56f1e40a8fd95
            args:
              - --run
              - --read-only-config
            env:
              TZ: *timeZone
            envFrom:
              - secretRef:
                  name: kometa-secret
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
        pod:
          restartPolicy: Never
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: node02
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    persistence:
      config:
        existingClaim: kometa
      config-file:
        type: configMap
        name: kometa-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
          - path: /config/filme.yml
            subPath: filme.yml
            readOnly: true
          - path: /config/serien.yml
            subPath: serien.yml
            readOnly: true
      genre-posters:
        type: custom
        volumeSpec:
          projected:
            sources:
              - configMap:
                  name: kometa-genre-posters-01
              - configMap:
                  name: kometa-genre-posters-02
              - configMap:
                  name: kometa-genre-posters-03
              - configMap:
                  name: kometa-genre-posters-04
              - configMap:
                  name: kometa-genre-posters-05
              - configMap:
                  name: kometa-genre-posters-06
              - configMap:
                  name: kometa-genre-posters-07
              - configMap:
                  name: kometa-genre-posters-08
              - configMap:
                  name: kometa-genre-posters-09
              - configMap:
                  name: kometa-genre-posters-10
              - configMap:
                  name: kometa-genre-posters-11
              - configMap:
                  name: kometa-genre-posters-12
              - configMap:
                  name: kometa-genre-posters-13
              - configMap:
                  name: kometa-genre-posters-14
              - configMap:
                  name: kometa-genre-posters-15
              - configMap:
                  name: kometa-genre-posters-16
        globalMounts:
          - path: /config/posters/genre
            readOnly: true
      universe-posters:
        type: custom
        volumeSpec:
          projected:
            sources:
              - configMap:
                  name: kometa-universe-posters-01
              - configMap:
                  name: kometa-universe-posters-02
              - configMap:
                  name: kometa-universe-posters-03
        globalMounts:
          - path: /config/posters/universe
            readOnly: true
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tmp:
        type: emptyDir
      assets:
        existingClaim: posterizarr-assets-pvc
        globalMounts:
          - path: /assets
            subPath: assets
