---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
spec:
  chartRef:
    kind: OCIRepository
    name: plugin-barman-cloud
  install:
    remediation:
      retries: 1
    timeout: 2m
  interval: 1h
  maxHistory: 1
  upgrade:
    remediation:
      retries: 1
    timeout: 2m
  values:
    image:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud
      tag: v0.15.1@sha256:c75acad19a36e8176cfe2885761ff1b836c6ef977d7257e298c99a28b5c302ef
    namespaceOverride: dbms
    sidecarImage:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud-sidecar
      tag: v0.15.1@sha256:2287a793a804db751edd0d07d44cd549e357677e98a800eb12e2cf7c0d53f9b0
