---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
spec:
  chartRef:
    kind: OCIRepository
    name: plugin-barman-cloud
  install:
    remediation:
      retries: 1
    timeout: 2m
  interval: 1h
  maxHistory: 1
  upgrade:
    remediation:
      retries: 1
    timeout: 2m
  values:
    image:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud
      tag: v0.13.0@sha256:71589dbac582333442812b07b31f7ea4d00324a8358aac7ca507dabf9f4b6c96
    namespaceOverride: dbms
    sidecarImage:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud-sidecar
      tag: v0.14.0@sha256:9880817c285c7afa4d195da2145064d21907405489ed6ec39abe59b1feb558a4
